apiVersion: v1
kind: Service
metadata:
  name: spring-boot-snippet-dev-service
  labels:
    app: spring-boot-snippet-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.103
  externalIPs:
  - 10.24.24.103
  ports:
  - name: http
    port: 83 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: spring-boot-snippet-dev #find all pod with app name
  sessionAffinity: None
