apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-snippet-dev
  namespace: spring-boot-snippet-dev
  labels:
    app: spring-boot-snippet-dev
spec:
  selector:
    matchLabels:
      app: spring-boot-snippet-dev
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-boot-snippet-dev
    spec:
      containers:
      - name: spring-boot-snippet-dev
        image: vincentbuiwork/spring-boot-snippet:dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 500M
          limits:
            cpu: 2
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: index.html
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
