apiVersion: v1
kind: Service
metadata:
  name: spring-boot-snippet-prod-service
  labels:
    app: spring-boot-snippet-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.103
  externalIPs:
  - 192.168.1.103
  ports:
  - name: http
    port: 80 #local out port
    protocol: TCP
    targetPort: 80 # container port
  selector:
    app: spring-boot-snippet-prod #find all pod with app name
  sessionAffinity: None
